### ISSUE TITLE
See if comments are disabled on the reply counter

### ISSUE THREAD

**Issue by sparkhom** [weeklybeats/issues#1]
From Judgement Act:
> very minor thing but it would be nice if we could see on the reply counter if comments were disabled. i like to listen by comments ascending and it always catches me out 😄

![image](https://github.com/weeklybeats/issues/assets/97196/0e1df8d8-0248-43c5-8aa0-3ab136f33bd8)

**Comment by arknano** [comment]
For what its worth I said this basically offhand and I realise the impact is very very low, given we only have a few people who disable comments 😄

**Comment by trash80** [comment]
Thanks, should be blank now if comments are disabled.
