### ISSUE TITLE
Implement an optimized 1200x630 opengraph image for sharing links on other SoMe

### ISSUE THREAD

**Issue by horatiu665** [weeklybeats/issues#12]
**Is your feature request related to a problem? Please describe.**
the og-image of the website doesn't show up on slack (or discord, or other places that generate link previews) because it's too heavy, 2.1mb png.

**Describe the solution you'd like**
make a 1200x630 format image with the wb graphic, and consider using jpg or optimizing it somehow to load faster. this would get rid of issues and make it nicer to share.

I could see when inspecting the page, there is already a meta tag in the <head> with the link. so it's just about making the new graphic. sorry I am not able to make the image myself to contribute
```
<head>
...
	<meta property="og:image" content="https://weeklybeats.com/images/wb2024-social.png">...
</head>
```

**Describe alternatives you've considered**

**Additional context**

**Comment by trash80** [comment]
I made it a jpg to reduce file size. Not planning on making a banner style graphic for now.
