### ISSUE TITLE
Profile page track list's new uploads have broken CSS

### ISSUE THREAD

**Issue by pibolib** [weeklybeats/issues#17]
**Describe the bug**
Submitting a new track and then viewing the profile page (BEFORE THE TRACK GOES LIVE) has broken CSS, causing all of the text to go one column to the left and the title to be squished into the side.

**To Reproduce**
Have a submitted but not released track
Go to profile page

**Expected behavior**
New tracks should appear like released tracks, just without a play button.

**Screenshots**
![image](https://github.com/weeklybeats/issues/assets/36494946/9d876a68-e15d-484a-b99c-9eb2d243c2ae)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Vivaldi
 - Version: 6.5.3206.53

**Additional context**
N/A

**Comment by trash80** [comment]
Should be fixed now I think?
