### ISSUE TITLE
Suddenly Can not upload

### ISSUE THREAD

**Issue by jackanderson** [weeklybeats/issues#21]
I have tried several times to upload my track for this week but it says "Error: Wrong type of file:"  
Ive tried several different files, including the file i successfully uploaded last week :< 
I dont see an error coming from the http request.. 

UPDATE: it works in edge, but not in chrome.

**Comment by sparkhom** [comment]
We talked offline, and it turns out that this is due to the McAfee WebAdvisor Chrome extension.
