### ISSUE TITLE
Downloads result in access denied

### ISSUE THREAD

**Issue by jimmac** [weeklybeats/issues#27]
**Describe the bug**
Haven't really tried to download a track ever. Getting an XML respose of a denied request.

**To Reproduce**
1. Go to any song, but say https://weeklybeats.com/as_yoesual/music/dropleton in particular.
2. Click on Download
4. See XML error: 
```
...
<Code>AccessDenied</Code>
<Message>Request has expired</Message>
```

**Expected behavior**
I get an mp3 back.

**Desktop (please complete the following information):**
 - OS: Fedora Linux 39.20240119.0 (Silverblue
 - Browser Firefox
 - Version 122

**Comment by sparkhom** [comment]
I think I know what the issue is; the download link is only valid for five minutes from the initial load of the page. Could you reload the page and try again?
