### ISSUE TITLE
Missing replies number on some profiles

### ISSUE THREAD

**Issue by JerwuQu** [weeklybeats/issues#31]
Some users are missing the Reply count on their tracks and instead have a blank space rather than "0".

Example of user with missing reply count: https://weeklybeats.com/monstrosus?s=&f=8&y=2024
![image](https://github.com/weeklybeats/issues/assets/3710677/faa2195c-8f7a-4647-bed5-b0128d41d49d)

Example of user with reply numbers:
![image](https://github.com/weeklybeats/issues/assets/3710677/d290630a-c2c7-477d-af29-6645184b1cd6)

Very easy to spot when sorting by replies: https://weeklybeats.com/music?p=1&s=&f=8&y=2024&t=&d=0&i=&o=comment_count

**Comment by sparkhom** [comment]
Hey, thanks for reporting! These are users that have turned off their comments, so they will have no replies. Working as intended.

**Comment by JerwuQu** [comment]
Ah! I didn't know this was a feature. Thanks!
