### ISSUE TITLE
Adding emoji to comment removes all comment text

### ISSUE THREAD

**Issue by sparkhom** [weeklybeats/issues#6]
> My comment just got killed because I put a unicode music note in it (there was text too) 

![image](https://github.com/weeklybeats/issues/assets/97196/a90ab48c-fffc-4050-b688-10a77a624024)

**Comment by judy** [comment]
I saw this one too, but I think it truncated the emoji and everything after it. The plain text comment I had up until the emoji stayed.

**Comment by trash80** [comment]
Think it should be resolved. Encoding needed to be updated.
